project:
  type: website
  output-dir: docs

website:
  site-url: https://arsenelaurent.github.io/
  title: "ArseneLaurent"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right: 
      - text: "Data Viz"
        menu: 
         - text: "London Marathon"
           href: LondonMarathon.html
         - text: "Campus Pride Index"
           href: pride.html

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

